sudo: false
language: go
go:
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  pip install --user codecov
install:
  - make setup
script:
  - make cover
after_success:
  codecov
